# Site settings
title: Euisuk's Dev Log
SEOTitle: Chung Euisuk | Data Scientist
header-img: img/home-bg.jpg
email: jasuchung@gmail.com
description: "Always be passionateüå±"
keyword: "Machine Learning, TimeSeries, Anomaly Detection, NLP, Vision, AI/ML, MLOps, AIOps"
url: "https://euisuk-chung.github.io"              # your host, for absolute URL
baseurl: ""  # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
instagram_username: chung_es
github_username:   euisuk-chung
youtube_username:  loading_700
linkedin_username:  euisuk-chung

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]

anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: your_disqus_shortname

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "ÏÑúÏø† Í∞úÎ∞úÎÖ∏Ìä∏‚≠ê <br> Data Scientist"
sidebar-avatar: https://github.com/euisuk-chung.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "My Velog", href: "https://velog.io/@euisuk-chung" },
    { title: "My YouTube", href: "https://www.youtube.com/@loading_700" },
    { title: "LGSW YouTube", href: "https://www.youtube.com/@lgsw" },
    { title: "DSBA Youtube", href: "https://www.youtube.com/@dsba2979" },
    { title: "DMQA Youtube", href: "https://www.youtube.com/@user-yu5qs4ct2b" }
  ]

# Include files
include:
  - "ads.txt"
  - "robots.txt"
  - "google35d12b88d96acbcd.html"

# SEO settings
author: "Euisuk Chung"
twitter:
  username: euisuk_chung
social:
  name: Euisuk Chung
  links:
    - https://github.com/euisuk-chung
    - https://www.linkedin.com/in/euisuk-chung
    - https://www.youtube.com/@loading_700
